In [13]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt

In [14]:
series = pd.Series(["Apple","Mango","Pineapple","Yam"])

In [15]:
series

0        Apple
1        Mango
2    Pineapple
3          Yam
dtype: str

In [16]:
price = pd.Series([100,200,300,400])

In [17]:
price

0    100
1    200
2    300
3    400
dtype: int64

In [18]:
fruits = pd.DataFrame({"fruits": series, "price": price,"color":color,"Type":Type})

In [19]:
fruits

      fruits  price   color       Type
0      Apple    100     Red       Pome
1      Mango    200  Yellow      Stone
2  Pineapple    300   Brown   Multiple
3        Yam    400   Green  Vegetable

In [20]:
color = pd.Series(["Red","Yellow","Brown","Green"])
color

0       Red
1    Yellow
2     Brown
3     Green
dtype: str

In [21]:

Type = pd.Series(["Pome","Stone","Multiple","Vegetable"])

In [22]:
car = pd.read_csv("car-details.csv")

In [23]:
car

   S/N CARTYPE  CAR-MAKE   COLOR  MODEL       PRICE  DISCOUNT
0    1     SUV    TOYOTA     RED   2025  10,000,000      0.25
1    2   SALON      BENZ  YELLOW   2026  20,000,000      0.15
2    3    JEEP       KIA   GREEN   2024  45,000,000      0.18
3    4     SUV       BMW    PINK   2023   5,000,000      0.13
4    5   SALON      AUDI   BLACK   2026  18,000,000      0.33
5    6    JEEP  PORABLES    BLUE   2027  32,000,000      0.50
6    7   SALON   BENTLEY  SILVER   2026  60,000,000      0.17